module snes_cart(
    input clk,
    input cs, // currently unused
    input spi_clk,
    input mosi,
    output miso
);
    wire byte_finished;
    wire [7:0] in_byte;
    wire [7:0] out_byte;
    wire [7:0] cmd;
    wire [7:0] arg1;
    wire [7:0] arg2;
    wire [7:0] cmd_crc8; // the 4th command byte
    wire frame_finished;
    wire [7:0] checksum_crc8; // generated by crc_manager
    wire [15:0] checksum_crc16; // generated by crc_manager
    wire cmd_reset;
    wire crc_reset;
    wire cmd_en;
    wire crc_en;

    spi_slave SPI_SLAVE(
        .spi_clk(spi_clk),
        .mosi(mosi),
        .out_byte(out_byte),
        .miso(miso),
        .in_byte(in_byte),
        .byte_finished(byte_finished)
    );

    cmd_manager CMD_MANAGER(
        .reset(cmd_reset),
        .en(cmd_en),
        .clk(clk),
        .in_byte(in_byte),
        .byte_finished(byte_finished),
        .cmd(cmd),
        .arg1(arg1),
        .arg2(arg2),
        .crc(cmd_crc8),
        .frame_finished(frame_finished)
    );

    crc_manager CRC_MANAGER(
        .reset(crc_reset),
        .en(crc_en),
        .spi_clk(spi_clk),
        .mosi(mosi),
        .crc8(checksum_crc8),
        .crc16(checksum_crc16)
    );

    brain BRAIN(
        // Inputs
        .clk(clk),
        .byte_finished(byte_finished),
        .frame_finished(frame_finished),
        .cmd(cmd),
        .arg1(arg1),
        .arg2(arg2),
        .checksum_crc8(checksum_crc8),
        .checksum_crc16(checksum_crc16),
        // Outputs
        .cmd_reset(cmd_reset),
        .crc_reset(crc_reset),
        .cmd_en(cmd_en),
        .crc_en(crc_en),
        .out_byte(out_byte)
    );
endmodule